### PR TITLE
Added support for node and npm

### PR DESCRIPTION
**Pull request by thepeak99**
Hi! 

I added support for node and to install it with npm. I would like to upload it to the npm registry, but I thought the best would be to merge this with you and upload your repo (it is your project after all :)

I updated the urls in the README and in package.json so they point to my repo, so before merging this with your code we should change that back to yours (or to the definitive npm registry url).

Danke schön!
Martin Zulliger

### CODE REVIEW

**Comment by Zod-** [comment]
Most of the changes in your commit shouldn't be in there. I will merge the code when you remove the changes in dist/ and tests/. I'll then make another release to add those changes

**Comment by thepeak99** [comment]
Ok! I'll get to it, thanks!

**Comment by revolunet** [comment]
hey, any plan to publish to npm ?
What changes do you need on this PR ?

**Comment by joonhocho** [comment]
+1

**Comment by DangelZM** [comment]
+1

**Comment by oyeanuj** [comment]
@thepeak99 @Zod- The plugin looks great, any chance this can be resolved to make it into an npm package?

**Comment by Zod-** [comment]
Sorry about this taking forever. 

I did the changes myself so this pull isn't needed anymore.

**Pull request closed without merging**
